
services:
  db_postgres:
    container_name: app-escola-postgres
    image: postgres:14.15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app-escola
    volumes:
      - /app-escola/src/database/postgres
    ports: 
      - "5432:5432"

  node:
    depends_on:
      - postgres
    container_name: app-escola-node
    image: node:20.18.1-alpine3.19
    volumes:
      - /app-escola/src
    ports: 
      - "3000:3000"
