
services:
  db_postgres:
    container_name: app-escola-db
    image: postgres:14.15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app-escola
    volumes: 
      - db_postgres:/var/lib/postgres
    ports: 
      - "5432:5432"

  node:
    build: .
    depends_on:
      - db_postgres
    container_name: app-escola-node
    volumes:
      - .:/src/
    ports: 
      - "3000:3000"

volumes:
    db_postgres:
    node: