name: Run Tests and Deploy

on:
  push:
    branches:
      - branch-fernanda
  pull_request:
    branches:
      - branch-fernanda

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
    
    steps:
      # Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Cache para dependências NPM
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Rodar testes com Jest
      - name: Run tests
        run: npm test

      # Condicional: Se os testes passarem, faça o deploy
      - name: Deploy to Production
        if: success()
        run: |
          echo "Deploying to production..."
          # Comando para deploy com Render (exemplo)
          render deploy --service <nome-do-serviço> --branch branch-fernanda
